/** Baseline: all pages, absence of old blocks, new functions and shared content. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {serve} from '../tools/serve.mjs';import {blockHTML} from '../tools/render-content.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const width=Number(process.env.QA_WIDTH)||1280,server=await serve(4285),browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width,height:900}});page.setDefaultTimeout(7000);const report={width,scope:'Baseline local; no authenticated AEM installation',tests:[]},pages=JSON.parse(fs.readFileSync('content/pages.json'));let errors=[];page.on('pageerror',e=>errors.push(e.message));
async function test(name,fn){errors=[];try{await fn();assert.deepEqual(errors,[]);report.tests.push({name,pass:true});console.log('OK',name)}catch(e){report.tests.push({name,pass:false,error:e.message,errors});console.log('FAIL',name,e.message)}}
async function visit(path){await page.goto('http://127.0.0.1:4285/'+(path==='index'?'':path));await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded);await page.waitForTimeout(100)}
try{
await test('Catálogo: 73 componentes Toranja React Adapter',async()=>{const groups=JSON.parse(fs.readFileSync('component-definition.json')).groups,defs=groups.flatMap(g=>g.components),blocks=defs.filter(d=>d.plugins.xwalk.page.resourceType==='core/franklin/components/block/v1/block');assert.equal(blocks.length,73);assert.ok(!groups.some(g=>g.id==='toranja-custom'));assert.ok(!groups.some(g=>g.id==='toranja'));assert.ok(blocks.every(b=>b.id.startsWith('ds-react-')));assert.equal(fs.existsSync('scripts/legacy-contracts.js'),false);assert.equal(fs.readdirSync('blocks').length,73);for(const p of Object.values(pages))for(const s of p.sections)for(const b of s.content)if(b.block)assert.ok(blocks.some(d=>d.id===b.block),b.block)});
for(const name of Object.keys(pages))await test('Página '+name,async()=>{await visit(name);assert.equal(await page.locator('main [data-block-name]').count(),pages[name].sections.reduce((n,s)=>n+s.content.filter(b=>b.block).length,0),'Todos os blocos renderizados');assert.deepEqual(await page.locator('[data-ds-error],[data-shared-error]').evaluateAll(ns=>ns.map(n=>n.dataset.dsError||n.dataset.sharedError)),[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.ok(await page.locator('main').innerText());assert.deepEqual(await page.locator('main [class]').evaluateAll(ns=>ns.filter(n=>[...n.classList].some(c=>/^ds-react-[a-z-]+$/.test(c)&&!['ds-official','ds-status','ds-author-items','ds-author-item','ds-tab-panel'].includes(c)&&!c.endsWith('-wrapper'))&&n.matches('[data-block-name]')&&n.dataset.dsMounted!=='true').map(n=>n.className)),[]);assert.deepEqual(await page.locator('main .block[data-block-name^="c-"]').evaluateAll(ns=>ns.filter(n=>n.dataset.toranjaReady!=='true').map(n=>n.dataset.blockName)),[]);if(!['nav','footer'].includes(name)){assert.equal(await page.locator('header[data-shared-ready=true]').count(),1);assert.equal(await page.locator('footer[data-shared-ready=true]').count(),1);}if(['index','composicoes','showcase/v3/formulario'].includes(name))await page.screenshot({path:'docs/baseline-'+name.replaceAll('/','-')+'-'+width+'.png',fullPage:true})});
await test('Abas oficiais preservam painéis migrados',async()=>{await visit('index');const tabs=page.locator('main .ds-react-tabs');await tabs.locator('[data-testid=tab]').nth(1).click();await tabs.getByRole('tabpanel').getByText('Gestão Financeira Completa para sua Empresa',{exact:true}).waitFor();assert.equal(await tabs.getByRole('tabpanel').getByText('Conta Digital PF 100% Gratuita',{exact:true}).count(),0)});
await test('Menu mobile abre e fecha por teclado',async()=>{await page.setViewportSize({width:390,height:900});await visit('index');const nav=page.getByRole('navigation',{name:'Navegação principal'});const menuButton=page.getByRole('button',{name:'Abrir menu',exact:true});const bounds=await menuButton.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390,'Menu integralmente visível');await menuButton.click();await nav.getByRole('link',{name:'Design System',exact:true}).waitFor({state:'visible'});await page.keyboard.press('Escape');await nav.getByRole('link',{name:'Design System',exact:true}).waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'Abrir menu',exact:true}).getAttribute('aria-expanded'),'false')});
}finally{fs.writeFileSync('docs/baseline-'+(process.env.QA_ROUND||'development')+'.json',JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}process.exitCode=report.tests.some(t=>!t.pass)?1:0;
