/** Compare computed presentation with a direct upstream consumer under identical site globals. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {serve} from '../tools/serve.mjs';import {blockHTML} from '../tools/render-content.mjs';
const cases=[['Button',{label:'Continuar',variant:'primary',size:'medium'}],['Text',{children:'Informação importante',textType:'body',textSize:'large',textWeight:'regular'}],['Link',{label:'Saiba mais',href:'/demo-toranja'}],['InputText',{label:'Nome',placeholder:'Digite seu nome'}],['InputPassword',{label:'Senha'}],['Select',{label:'Produto',options:[{label:'Conta',value:'conta'},{label:'Crédito',value:'credito'}],value:'conta'}],['Stepper',{min:0,max:10,value:4,enableInput:true,state:'enabled',mask:false,maskType:'BRL'}],['SectionSubtitle',{children:'Seu catálogo',as:'h2'}],['SegmentedControl',{segments:[{label:'Pessoal'},{label:'Empresas'}]}],['Pagination',{pageIndex:0,pageSize:10,pageCount:5,totalItems:50,pageSizeOptions:[10,25,50]}],['Breadcrumb',{items:[{id:'home',label:'Home',href:'/'},{id:'current',label:'Catálogo'}]}]];
const models=JSON.parse(fs.readFileSync('component-models.json'));const schemas=JSON.parse(fs.readFileSync('docs/property-mapping.json')),allSamples=JSON.parse(fs.readFileSync('content/ds-samples.json'));
const server=await serve(4302),browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const report={scope:'Direct upstream 2.0.1 bundle versus EDS adapter; computed CSS for critical and changed components across 4 themes and 2 widths; not exhaustive combinations.',checks:[]};
function authored(name,props){const [id,s]=Object.entries(schemas).find(([id,s])=>s.name===name),b={block:id,properties:Object.fromEntries(models.find(m=>m.id===id).fields.map(f=>[f.name,''])),items:[]};const at=(o,p)=>p.reduce((v,k)=>v?.[k],o);for(const d of s.descriptors){const v=at(props,d.path);if(v!==undefined)b.properties[d.key]=['json','array'].includes(d.kind)?JSON.stringify(v):v;}for(const c of s.collections){const items=at(props,c.path);if(!Array.isArray(items))continue;for(const item of items){const row={collection:c.id};for(const d of c.descriptors){const v=at(c.primitive?{value:item}:item,d.path);if(v!==undefined)row[d.key]=['array','json'].includes(d.kind)?JSON.stringify(v):v;}b.items.push(row)}}return b}
const styles=['fontFamily','fontSize','fontWeight','lineHeight','color','backgroundColor','borderTopColor','borderTopWidth','borderRadius','paddingTop','paddingRight','paddingBottom','paddingLeft','gap','display','alignItems','justifyContent','width','height'];
try{for(const width of (process.env.QA_QUICK?[393]:[393,1440]))for(const theme of (process.env.QA_QUICK?['pf-light']:['pf-light','pf-dark','pj-light','pj-dark'])){
 const adapter=await browser.newPage({viewport:{width,height:1000}}),reference=await browser.newPage({viewport:{width,height:1000}});
 for(const [name,props] of cases){try{
  const markup=blockHTML(authored(name,props));
  await adapter.goto('http://127.0.0.1:4302/');await adapter.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded==='true');
  await adapter.evaluate(async({markup,theme})=>{document.documentElement.setAttribute('toranja-theme',theme);document.body.innerHTML='<main>'+markup+'</main>';const b=document.querySelector('main').firstElementChild;await(await import('/blocks/'+b.className+'/'+b.className+'.js')).default(b);},{markup,theme});
  await reference.goto('http://127.0.0.1:4302/docs/reference-runtime/reference.html');
  await reference.evaluate(({theme,name,props,markup})=>{document.documentElement.setAttribute('toranja-theme',theme);document.querySelector('main').innerHTML=markup;document.querySelector('main').firstElementChild.innerHTML='<div class="ds-official" id="reference"></div>';window.renderOfficial(name,props)},{theme,name,props,markup});
  for(const page of [adapter,reference])await page.evaluate(async()=>{const style=document.createElement('style');style.textContent='*,*::before,*::after{transition:none!important;animation:none!important}';document.head.append(style);await document.fonts.ready;await new Promise(r=>setTimeout(r,1200));document.activeElement?.blur()});
  const snapshot=async page=>page.locator('main .ds-official').evaluate((host,styles)=>[...host.querySelectorAll('*')].filter(el=>!el.closest('svg')&&!el.matches('.ds-status')).map(el=>({tag:el.tagName,class:el.className,text:el.children.length?'':el.textContent,css:Object.fromEntries(styles.map(k=>[k,getComputedStyle(el)[k]]))})),styles);
  const actual=await snapshot(adapter),expected=await snapshot(reference);if(JSON.stringify(actual)!==JSON.stringify(expected))fs.writeFileSync('docs/parity-diff-'+name+'.json',JSON.stringify({actual,expected},null,2));assert.deepEqual(actual,expected);report.checks.push({name,width,theme,pass:true,nodes:actual.length});
 }catch(e){report.checks.push({name,width,theme,pass:false,error:e.message.slice(0,2000)});console.log('FAIL',name,width,theme,e.message.slice(0,300))}}
 await adapter.close();await reference.close();}
}finally{fs.writeFileSync('docs/official-parity-v4.0.0.json',JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r))}
console.log(report.checks.filter(x=>x.pass).length+'/'+report.checks.length+' comparisons match');process.exitCode=report.checks.some(x=>!x.pass)?1:0;
