/** Contract changes in Toranja 2.0.1: real controls, portals, and controlled props. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {serve} from '../tools/serve.mjs';import {blockHTML} from '../tools/render-content.mjs';
const server=await serve(4301),browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:Number(process.env.QA_WIDTH)||393,height:900}});page.setDefaultTimeout(6000);
const samples=JSON.parse(fs.readFileSync('content/ds-samples.json'));const checks=[];let errors=[];page.on('pageerror',e=>errors.push(e.message));
const key=p=>'p'+Buffer.from(p).toString('hex');
async function mount(name,props={}){await page.goto('http://127.0.0.1:4301/');await page.waitForFunction(()=>document.documentElement.dataset.toranjaLoaded==='true');const b=structuredClone(samples.find(b=>b.block===name));Object.assign(b.properties,props);await page.evaluate(async({html,name})=>{document.querySelector('main').innerHTML=html;await(await import('/blocks/'+name+'/'+name+'.js')).default(document.querySelector('main').firstElementChild);},{html:blockHTML(b),name});await page.waitForTimeout(150);}
async function test(name,fn){errors=[];try{await fn();assert.deepEqual(errors,[]);checks.push({name,pass:true});console.log('OK',name)}catch(e){checks.push({name,pass:false,error:e.message,errors});console.log('FAIL',name,e.message)}}
try{
await test('Select official options update controlled value',async()=>{await mount('ds-select');await page.locator('main .select__trigger').click();await page.getByRole('option',{name:'Crédito',exact:true}).click();assert.equal(await page.locator('main input').inputValue(),'Crédito')});
await test('Stepper controlled value starts at 4 and changes to 5',async()=>{await mount('ds-stepper',{[key('value')]:4,[key('min')]:0,[key('max')]:10});assert.equal(await page.locator('main input').inputValue(),'4');await page.locator('main button').last().click();assert.equal(await page.locator('main input').inputValue(),'5')});
await test('MenuPopup portal keeps official CSS and keyboard closure',async()=>{await mount('ds-menu-popup');await page.getByRole('button',{name:'Abrir MenuPopup'}).click();const menu=page.getByRole('menu');await menu.waitFor();assert.equal(await menu.evaluate(e=>getComputedStyle(e).position),'fixed');assert.ok((await menu.boundingBox()).width>=160);await page.keyboard.press('Escape');await menu.waitFor({state:'hidden'})});
await test('ModalDialog official portal opens and closes',async()=>{await mount('ds-modal-dialog');await page.getByRole('button',{name:'Abrir ModalDialog'}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();assert.equal(await page.locator('body > .overlay').evaluate(e=>getComputedStyle(e).position),'fixed');assert.equal(await page.locator('.modal-dialog').evaluate(e=>getComputedStyle(e).position),'fixed');await page.getByRole('button',{name:'Fechar',exact:true}).click();await dialog.waitFor({state:'hidden'})});
await test('SideSheet opens its official panel',async()=>{await mount('ds-side-sheet');await page.getByRole('button',{name:'Abrir SideSheet'}).click();await page.getByText('Conteúdo editável do painel lateral.').waitFor({state:'visible'})});
await test('TooltipDescription portal retains placement styles',async()=>{await mount('ds-tooltip-description');await page.getByRole('button',{name:'Abrir TooltipDescription'}).hover();const tip=page.getByRole('tooltip');await tip.waitFor();assert.equal(await tip.evaluate(e=>getComputedStyle(e).position),'fixed');assert.equal(Math.round((await tip.boundingBox()).width),280)});
await test('Table receives record rows and keyed columns',async()=>{await mount('ds-table');await page.getByRole('cell',{name:'Conta Digital',exact:true}).waitFor();await page.getByRole('cell',{name:'Crédito',exact:true}).waitFor();assert.equal(await page.locator('[data-ds-error]').count(),0)});
await test('Table controlled selection remains interactive',async()=>{await mount('ds-table',{[key('selectedRowIds')]:'{}',[key('selectionColumn.position')]:'START'});const checkbox=page.getByRole('checkbox').nth(1);await checkbox.check();if(!await checkbox.isChecked())throw Error('Controlled selection did not update')});
await test('Sidebar retains expanded navigation and brand',async()=>{await mount('ds-sidebar');await page.locator('main').getByText('Catálogo',{exact:true}).waitFor();assert.ok(await page.locator('main img,main svg').count())});
await test('Breadcrumb retains real home link',async()=>{await mount('ds-breadcrumb');assert.equal(await page.locator('main').getByRole('link',{name:'Home',exact:true}).getAttribute('href'),'/')});
await test('Pagination renders a populated page range',async()=>{await mount('ds-pagination');assert.ok(await page.locator('main button').count());assert.ok((await page.locator('main').innerText()).includes('50'))});
}finally{fs.writeFileSync('docs/toranja-v2-validation-'+(process.env.QA_WIDTH||393)+'.json',JSON.stringify({scope:'Local browser; public Toranja 2.0.1 APIs and portal styles',checks},null,2));await browser.close();await new Promise(r=>server.close(r))}process.exitCode=checks.some(t=>!t.pass)?1:0;
