"""Build a report from the completed, passing local baseline audits."""
from pathlib import Path
import json,html,hashlib
root=Path(__file__).resolve().parents[1];docs=root/'docs';h=html.escape
suites=[('baseline','Páginas e baseline'),('validation','64 componentes oficiais'),('acceptance','Interações e eventos de autoria simulados'),('v3','Funcionalidades e contratos V3'),('v3-content','Novas instâncias, temas e conteúdo')]
rows=[];total=0;records=[]
for n in [1,2]:
 for prefix,label in suites:
  path=docs/f'{prefix}-baseline-final-{n}.json';report=json.loads(path.read_text());tests=report['tests'];passed=sum(t['pass'] for t in tests)
  if passed!=len(tests):raise RuntimeError('Auditoria reprovada: '+path.name)
  rows.append(f'<tr><td>{n}</td><td>{h(label)}</td><td>{passed}/{len(tests)}</td><td><a href="{path.name}">Evidência JSON</a></td></tr>');total+=len(tests);records.append({'round':n,'suite':label,'passed':passed,'total':len(tests),'report':path.name})
for name,key in [('baseline-package-validation.json','tests'),('package-audit.json','checks')]:
 if not all(t['pass'] for t in json.loads((docs/name).read_text())[key]):raise RuntimeError('Pacote reprovado: '+name)
migration=json.loads((docs/'baseline-conversion.json').read_text());package=root/'content/demo-to-content.zip';digest=hashlib.sha256(package.read_bytes()).hexdigest()
summary={'version':'3.0.1','baseline':'V3','reference':'@interco/inter-toranja 1.13.3','officialComponents':64,'classifiedOwnProperties':751,'functionalBlocks':4,'removedOldBlocks':31,'pages':113,'assets':11,'browserAssertions':total,'rounds':records,'contentPackageSHA256':digest,'remoteInstallationTested':False,'remoteUEPersistenceTested':False}
(docs/'baseline-summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2))
old=', '.join(migration['removedBlockIds'])
body=f'''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V3 baseline — auditoria Toranja EDS</title><style>
:root{{color-scheme:light}}*{{box-sizing:border-box}}body{{margin:0;background:#f6f5f2;color:#222;font:16px/1.6 system-ui,sans-serif}}main{{max-width:1100px;margin:auto;padding:48px 24px}}header{{border-top:8px solid #ff7a00;padding-top:24px}}h1{{font-size:clamp(32px,6vw,58px);letter-spacing:-2px;line-height:1.08;margin:16px 0}}h2{{margin-top:36px}}.eyebrow{{font-weight:700;letter-spacing:2px;font-size:13px}}.metrics{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:28px 0}}.metric,section{{padding:24px;background:white;border:1px solid #dedbd4;border-radius:12px}}.metric strong{{display:block;font-size:32px}}section{{margin-top:20px}}table{{border-collapse:collapse;width:100%}}th,td{{border-bottom:1px solid #ddd;padding:12px 8px;text-align:left}}.table{{overflow:auto}}a{{color:#ad4800}}code{{overflow-wrap:anywhere;font-size:13px}}.note{{border-left:4px solid #ff7a00;padding-left:20px}}@media(max-width:700px){{.metrics{{grid-template-columns:repeat(2,1fr)}}main{{padding:24px 16px}}section{{padding:18px}}}}
</style><main><header><div class="eyebrow">TORANJA / EDGE DELIVERY SERVICES</div><h1>V3 como baseline exclusiva.</h1><p>Versão técnica 3.0.1 • DS oficial 1.13.3 • 5 de outubro de 2026</p></header><div class="metrics"><div class="metric"><strong>64/64</strong>componentes oficiais</div><div class="metric"><strong>113</strong>páginas preservadas</div><div class="metric"><strong>31</strong>blocos antigos retirados</div><div class="metric"><strong>{total}</strong>verificações de navegador</div></div>
<p class="note"><b>Escopo da evidência:</b> duas rodadas locais em Chromium, com páginas a 1280 e 390 pixels e eventos Universal Editor simulados. A suíte de aceitação de interações usa viewport fixo de 900 pixels. Não foi executada instalação, publicação ou persistência autenticada no seu AEM.</p>
<section><h2>O que mudou</h2><p>O catálogo contém apenas estrutura de conteúdo, os 64 componentes oficiais e quatro funcionalidades V3: formulário, busca, vídeo e simulador. Foram migrados 67 usos da implementação anterior. Cabeçalho e rodapé são composições oficiais nas páginas compartilhadas nav e footer.</p><p>Foram corrigidos o identificador do formulário, o painel de conteúdo das abas, a largura do skeleton do Accordion no mobile e o posicionamento do menu. O snapshot do DS permanece preservado; adaptações ficam fora do vendor.</p><p><b>Implementações retiradas:</b> {h(old)}.</p></section>
<section><h2>Cobertura e flexibilidade</h2><p>751 propriedades próprias estão classificadas nos contratos. Campos, coleções tipadas e ações são representados no editor; callbacks e referências técnicas têm contratos de integração, sem execução de JavaScript arbitrário informado pelo autor. O catálogo gera 101 modelos e 2.198 campos, incluindo itens.</p><p>64/64 é cobertura dos exports públicos do snapshot, não certificação de todas as combinações possíveis. Serviços produtivos permanecem por integrar. A busca consulta o índice público EDS do conteúdo AEM; o simulador é demonstrativo.</p><p><a href="property-mapping.json">Mapeamento das propriedades</a> · <a href="cobertura-propriedades.csv">Inventário CSV</a> · <a href="baseline-conversion.json">Conversão do conteúdo</a></p></section>
<section><h2>Duas rodadas finais</h2><div class="table"><table><thead><tr><th>Rodada</th><th>Escopo</th><th>Aprovados</th><th>Registro</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p>Mais seis verificações do pacote/ferramentas e nove gates de empacotamento aprovados. Os testes verificam escopo dos filtros, ausência de blocos antigos, planejamento de URLs e sincronização local sem perda do Git/configuração.</p><p><a href="baseline-package-validation.json">Pacote e ferramentas</a> · <a href="package-audit.json">Gates de entrega</a></p></section>
<section><h2>Reimportação</h2><p>O ZIP interno contém 113 páginas e 11 assets. O filtro substitui descendentes de <code>/content/demo-to</code>, inclusive páginas ausentes da baseline, e exclui o <code>jcr:content</code> da raiz. Não altera <code>/conf</code>, outros sites ou assets fora dos filtros exatos.</p><p><b>Faça backup.</b> Despublique URLs obsoletas antes da importação. Sincronize o clone para registrar também as exclusões, envie o commit, instale o ZIP interno e publique as páginas e referências. A configuração do EDS e as permissões da conta técnica continuam necessárias.</p><p><a href="DEPLOY-V3-BASELINE.md">Procedimento completo</a> · <a href="INTEGRACOES-V3.md">Integrações</a></p><p>SHA-256 do pacote de conteúdo:<br><code>{digest}</code></p></section>
<section><h2>Homologação pendente na instância</h2><p>Conferir instalação e remoção de conteúdo antigo, catálogo carregado da branch correta, salvar/reabrir propriedades, adicionar/reordenar/remover itens, acesso público por <code>/</code>, publicação das 113 páginas, índice de busca e retirada das URLs obsoletas. Só após essas etapas o ambiente remoto estará confirmado como exclusivamente V3.</p></section></main></html>'''
(docs/'AUDITORIA-V3-BASELINE.html').write_text(body)
print('Relatório gerado:',total,'verificações de navegador aprovadas; nenhuma validação remota presumida.')
