import fs from 'node:fs';
const pages=JSON.parse(fs.readFileSync('content/pages.json')),schema=JSON.parse(fs.readFileSync('scripts/ds-schema.json'));
function block(id,props={},groups={}){
 const s=schema[id],b={block:id,properties:{schemaVersion:'toranja-v3'},items:[]};
 for(const [path,value] of Object.entries(props)){const d=s.descriptors.find(d=>d.path.join('.')===path);if(!d)throw Error(id+' propriedade ausente '+path);b.properties[d.key]=value;}
 for(const [id,values] of Object.entries(groups)){const c=s.collections.find(c=>c.id===id);if(!c)throw Error('Coleção ausente '+id);for(const value of values){const row={collection:id};for(const d of c.descriptors){const v=d.path.reduce((v,k)=>v?.[k],value);if(v!==undefined)row[d.key]=v;}b.items.push(row);}}
 return b;
}
const page=(title,description,content)=>({title,description,sections:[{content:[{text:'<h1>'+title+'</h1><p>'+description+'</p><p><a href="/showcase/v3">Voltar às novidades V3</a></p>'},...content]}]});
pages['showcase/v3']=page('Toranja EDS V3','Exemplos editáveis de propriedades, interações e composição.',[{text:'<ul><li><a href="/showcase/v3/formulario">Formulário configurável</a></li><li><a href="/showcase/v3/controles">Controles e listas</a></li><li><a href="/showcase/v3/composicao">Cards e carrossel</a></li><li><a href="/showcase/v3/dados">Dados e gráficos</a></li><li><a href="/showcase/v3/acoes">Ações e painel</a></li><li><a href="/showcase/v3/video">Vídeo responsivo</a></li></ul>'}]);
pages['showcase/v3/formulario']=page('Formulário configurável','Adicione, reordene e configure os campos. O envio fica disponível quando uma integração for cadastrada.',[{block:'form',properties:{title:'Converse com nosso time',titleType:'h2',submitLabel:'Enviar solicitação',integrationId:'inter-lead',consent:'<p>Li e concordo com a <a href="/politica-de-privacidade">política de privacidade</a>.</p>'},items:[{fieldName:'nome',label:'Nome',kind:'text',required:true},{fieldName:'email',label:'E-mail',kind:'email',required:true},{fieldName:'interesse',label:'Tenho interesse em',kind:'select',options:'<ul><li>Conta | conta</li><li>Crédito | credito</li></ul>',required:true},{fieldName:'cpf',label:'CPF',kind:'cpf',required:true,showWhenField:'interesse',showWhenOperator:'equals',showWhenValue:'credito',hint:'Este campo aparece apenas para a opção Crédito.'},{fieldName:'mensagem',label:'Mensagem',kind:'textarea',maxLength:500}]}]);
pages['showcase/v3/controles']=page('Controles e listas','Os valores iniciais e as variantes podem ser alterados no painel.',[block('ds-list-item',{label:'Receber novidades','leadingCheckbox.checked':true,'$leadingChoice':'leadingCheckbox','$trailingChoice':'none',state:'enabled'}),block('ds-list-item-control',{label:'Quantidade','trailingVariant':'stepper','trailingProps.value':5,'trailingProps.min':0,'trailingProps.max':10,'trailingProps.step':1,state:'enabled'}),block('ds-select',{label:'Escolha um produto'}, {'$options':[{label:'Conta',value:'conta'},{label:'Crédito',value:'credito'}]})]);
pages['showcase/v3/composicao']=page('Composição de conteúdo','Adicione itens de texto, imagem, ação ou cartão e reorganize a sequência.',[block('ds-card',{state:'enabled'},{'content:children':[{kind:'text',title:'Uma experiência editável',body:'<p>Conteúdo e apresentação separados para facilitar a manutenção.</p>'},{kind:'button',label:'Conhecer os componentes',href:'/demo-toranja'}]}),block('ds-carousel',{showPreview:true,pageWidth:320},{items:[{kind:'card',title:'Conta digital',value:'<p>Organize sua vida financeira.</p>',href:'/conta-digital',label:'Conhecer'},{kind:'card',title:'Mais possibilidades',value:'<p>Uma composição com conteúdo próprio em cada slide.</p>',href:'/demo-toranja',label:'Explorar'}]})]);
pages['showcase/v3/dados']=page('Dados estruturados','Cada item mantém categoria e valor juntos. Uma fonte de dados cadastrada pode substituir os dados editoriais.',[block('ds-chart-bar',{state:'enabled',size:'large'},{chartData:[{label:'Janeiro',value:18},{label:'Fevereiro',value:32},{label:'Março',value:45}]}),block('ds-chart-donut',{state:'enabled'},{chartData:[{label:'Conta',value:60},{label:'Crédito',value:25},{label:'Outros',value:15}]})]);
pages['showcase/v3/acoes']=page('Ações independentes','Um botão abre o painel pelo identificador configurado; outro mantém seu próprio destino.',[block('ds-button',{label:'Abrir detalhes','$actions.onClick.kind':'open','$actions.onClick.id':'painel-v3'}),block('ds-button',{label:'Abrir catálogo','$actions.onClick.kind':'navigate','$actions.onClick.link':'/demo-toranja','$actions.onClick.target':'_self'}),block('ds-bottom-sheet',{title:'Detalhes',slot:'<p>Este painel foi aberto por uma ação configurável.</p>',overlay:'on',position:'hug','$overlayId':'painel-v3','$showTrigger':false})]);
pages['showcase/v3/video']=page('Player responsivo','Arquivo local de demonstração técnica com legendas. O componente também aceita YouTube e arquivos diretos.',[{block:'video-player',properties:{videoUrl:'/assets/demo/player-v3.mp4',posterImage:'/assets/demo/ec9cc3472288.jpg',posterImageAlt:'Capa demonstrativa do player',title:'Demonstração técnica',caption:'Conteúdo de teste do player. Não é um vídeo institucional.',ratio:'16/9',captionsUrl:'/assets/demo/player-v3.vtt',captionsLanguage:'pt-BR',captionsLabel:'Português',classes_portalVariant:'rounded'}}]);
// Remove o vídeo externo inadequado que existia na demonstração anterior.
for(const p of Object.values(pages))for(const s of p.sections)for(const b of s.content)if(b.block==='video-player'){b.properties.videoUrl='/assets/demo/player-v3.mp4';b.properties.posterImageAlt='Capa demonstrativa do player';b.properties.caption='Conteúdo de teste do player. Não é um vídeo institucional.';b.properties['classes_portal-variant']='rounded';delete b.properties.classes_portalVariant;}
if(!pages['politica-de-privacidade'])pages['politica-de-privacidade']=page('Política de privacidade','Página de demonstração: substitua pelo conteúdo aprovado antes de publicar.',[]);
if(!pages['conta-digital'])pages['conta-digital']=page('Conta digital','Página de demonstração.',[]);
const catalog=pages['demo-toranja'].sections[0].content;if(!catalog.some(b=>b.text?.includes('/showcase/v3')))catalog.splice(1,0,{text:'<p><a href="/showcase/v3">Conheça as configurações e interações da V3</a></p>'});
fs.writeFileSync('content/pages.json',JSON.stringify(pages,null,2));console.log('Showcase V3 atualizado.');
